import flightGroupClass as g
grouptest = g.FlightGroup.from_input() # This will open an instance of a group generated by user input
#grouptest = g.FlightGroup.from_file()
grouptest.printinfo()
#grouptest.save()

#grouptest2 = g.FlightGroup.from_file()
#grouptest2.printinfo()